MAX_ANSWER_LENGTH = 23
MASK_DECAY_RATE = 1
ANSWER_VOCABULARY_SIZE = 28
MAX_CLUE_LENGTH = 31

ENCODER = 'microsoft/deberta-v3-base'
DECODER_MAX_SEQUENCE_LENGTH = MAX_ANSWER_LENGTH
DECODER_EMBEDDING_DIMENSIONS = 768
DECODER_LAYER_ATTENTION_HEAD_COUNT = 12
DECODER_LAYER_FEEDFORWARD_DIMENSIONS = 3072
DECODER_LAYER_COUNT = 12
CLASSES_COUNT = 26

CLUES_SPLIT = 'data/clues_split_overfit_duplicate_100_answers'
BATCH_SIZE = 1
LEARNING_RATE = 1e-5
EPOCHS = 100000
EVALUATION_INTERVAL = 1
CHECKPOINT_TITLE = 'checkpoints/duplicate_100_answers_2.pth'
RUN = 'duplicate_100_answers'
